spring:
  datasource:
#    name:
    username: root
    password: 8750
    profiles:
      active: dev,redisPool
#    url: jdbc:mysql://127.0.0.1:3306/myblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC


logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml





# Jedis
jedis:
  host: 127.0.0.1
  port: 6379
  #password: 123456